In [32]:
import random
import numpy as np
a = range(10)
data = np.array([[1,3],[4,2],[5,6]])
print data
print "-------"
print np.sort(data, axis=1)
print "-------"

print np.argsort(data, axis = None )  # [0 3 1 2 4 5]
index = np.unravel_index(np.argsort(data, axis = None), data.shape) #(array([0, 1, 0, 1, 2, 2]), array([0, 1, 1, 0, 0, 1]))
print index
index[1]
index[1][:3]
print "-------"
a = data[np.newaxis,:,:]
print a
a.shape
print "-------"
data.reshape(1,3,2)

[[1 3]
 [4 2]
 [5 6]]
-------
[[1 3]
 [2 4]
 [5 6]]
-------
[0 3 1 2 4 5]
(array([0, 1, 0, 1, 2, 2]), array([0, 1, 1, 0, 0, 1]))
-------
[[[1 3]
  [4 2]
  [5 6]]]
-------


array([[[1, 3],
        [4, 2],
        [5, 6]]])

In [29]:
data = np.array([[[2,1],[9,8]], [[10,4],[6,5]]])
print data
#print np.sort(data, axis = 0)

# np.unravel_index()

[[[ 2  1]
  [ 9  8]]

 [[10  4]
  [ 6  5]]]
[[[0 0]
  [1 1]]

 [[1 1]
  [0 0]]]


In [69]:
x = np.array([3,3,2,2,0,1,3])
a = np.bincount(x)
print a
b = np.array([4,7,2])
a.argmax()

[1 1 2 3]


3

In [75]:
macros = np.array([
  [0.3, 2.5, 3.5],
  [2.9, 27.5, 0],
  [0.4, 1.3, 23.9],
  [14.4, 6, 2.3]])
cal_per_macro = np.array([9, 4, 4])
macros * cal_per_macro


(3,)

In [16]:
data = np.array([[1,3],[4,2],[5,6]])
a = np.array([1,2])
b = np.array([3,4,5])
print a.shape
print a.reshape(1,2).shape
data.shape
data - a

print a.reshape(2,1) - a.reshape(1,2)

(2,)
(1, 1, 2)
[[ 0 -1]
 [ 1  0]]


In [22]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis]

array([[  0.],
       [ 10.],
       [ 20.],
       [ 30.]])

In [40]:
a = np.array([1,2])
b = np.array([3,4,5])
print a.shape
print b.shape
aa = a.reshape(2,1)
bb =b.reshape(1,3)
aa - bb

(2,)
(3,)


array([[-2, -3, -4],
       [-1, -2, -3]])

In [43]:
a = np.arange(20)
b = np.array_split(a, 5)
b[:1] + b[2:]


[array([0, 1, 2, 3]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15]),
 array([16, 17, 18, 19])]

In [50]:
# a = np.array([[1,2,3],[4,5,6]])
a = np.array([1,2,3])
np.vstack([a,a,a] + [a,a])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [58]:
a = np.array([-110,2,3])
np.exp(a)
1 / (1+np.exp(-a))

array([  1.68891188e-48,   8.80797078e-01,   9.52574127e-01])

In [52]:
1+ np.exp(a)

array([  3.71828183,   8.3890561 ,  21.08553692])

In [71]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])
c = np.array([7,8])
print a.shape
print b.shape
(a.dot(b))
(b.reshape((2,1)).dot(c.reshape((1,2))))
a[1][1]

(2, 2)
(2,)


4

In [72]:
[x+1 for x in xrange(10)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [79]:
a = np.array([1,2,3,4]);
a > 1
a.shape

(4,)

In [78]:
np.hstack([np.array([0]), a])

array([0, 1, 2, 3, 4])

In [85]:
data = np.array([[1,3],[4,2],[5,6]])
print data
data > 5
data[data > 5]  = 10 
data

[[1 3]
 [4 2]
 [5 6]]


array([[ 1,  3],
       [ 4,  2],
       [ 5, 10]])

In [90]:
a = "afefe"
print a
a == "afefe"

afefe


True

In [3]:
import numpy as np
a = np.array([1,1,1,9,9,9,0])
np.bincount(a)

array([1, 3, 0, 0, 0, 0, 0, 0, 0, 3])